repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'master'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v2.1.0
#    hooks:
#    - id: flake8
